version: '3.9'

services:

  db:
    image: postgres
    container_name: go-simple-crud-example-db
    environment:
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASS:-root}
      - POSTGRES_DB=${DB_NAME:-go-simple-crud-example}
#      - DATABASE_HOST=${DB_HOST}
    ports:
      - ${DB_PORT:-5436}:5432
    volumes:
        - db:/var/lib/postgresql/data/
volumes:
  db: